
export const students = [
  {
    id: 1,
    name: "Ada",
    city: "Ankara",
    isActive: true,
    scores: [82, 91, 77],
    attendance: 0.92,
    enrolledCourses: ["js101", "git", "node"],
  },
  {
    id: 2,
    name: "Bora",
    city: "İstanbul",
    isActive: false,
    scores: [55, 60, 58],
    attendance: 0.61,
    enrolledCourses: ["js101", "html", "css"],
  },
  {
    id: 3,
    name: "Cem",
    city: "İzmir",
    isActive: true,
    scores: [95, 88, 92],
    attendance: 0.97,
    enrolledCourses: ["js101", "git", "node", "algorithms"],
  },
  {
    id: 4,
    name: "Deniz",
    city: "Bursa",
    isActive: true,
    scores: [73, 70, 68],
    attendance: 0.81,
    enrolledCourses: ["js101", "css", "git"],
  },
  {
    id: 5,
    name: "Ece",
    city: "Ankara",
    isActive: true,
    scores: [88, 84, 91],
    attendance: 0.89,
    enrolledCourses: ["js101", "node"],
  },
  {
    id: 6,
    name: "Fırat",
    city: "Antalya",
    isActive: false,
    scores: [40, 52, 47],
    attendance: 0.49,
    enrolledCourses: ["html", "css"],
  },
  {
    id: 7,
    name: "Gizem",
    city: "Eskişehir",
    isActive: true,
    scores: [66, 74, 72],
    attendance: 0.76,
    enrolledCourses: ["js101", "git"],
  },
  {
    id: 8,
    name: "Hakan",
    city: "İstanbul",
    isActive: true,
    scores: [90, 93, 87],
    attendance: 0.95,
    enrolledCourses: ["js101", "algorithms"],
  },
  {
    id: 9,
    name: "İpek",
    city: "Ankara",
    isActive: true,
    scores: [61, 69, 64],
    attendance: 0.83,
    enrolledCourses: ["js101", "git", "css"],
  },
  {
    id: 10,
    name: "Kemal",
    city: "Trabzon",
    isActive: true,
    scores: [78, 80, 75],
    attendance: 0.9,
    enrolledCourses: ["js101", "node", "git"],
  },
  {
    id: 11,
    name: "Lale",
    city: "İzmir",
    isActive: false,
    scores: [59, 62, 55],
    attendance: 0.57,
    enrolledCourses: ["html", "css", "design"],
  },
  {
    id: 12,
    name: "Mert",
    city: "Kayseri",
    isActive: true,
    scores: [85, 82, 78],
    attendance: 0.88,
    enrolledCourses: ["js101", "git", "node"],
  },
];

export const courses = [
  { code: "js101", title: "JavaScript Temelleri", hours: 40 },
  { code: "git", title: "Git & GitHub", hours: 12 },
  { code: "node", title: "Node.js Giriş", hours: 24 },
  { code: "html", title: "HTML", hours: 16 },
  { code: "css", title: "CSS", hours: 18 },
  { code: "algorithms", title: "Algoritmalar", hours: 30 },
  { code: "design", title: "Tasarım Temelleri", hours: 20 },
];
